import { Bot, LoaderCircle, RefreshCw } from 'lucide-react'
import { useEffect,useRef,useState } from 'react'
import { api } from '../api'
const SCRIPT=import.meta.env.VITE_WOOBE_EMBED_SCRIPT_URL??'http://localhost:8081/chat/v1/embed.js';const IFRAME=import.meta.env.VITE_WOOBE_IFRAME_BASE_URL??'http://localhost:8081/chat/v1';const WOOBE=import.meta.env.VITE_WOOBE_API_BASE_URL??'http://localhost:8000'
let loader:Promise<void>|null=null
function load(){if(window.WoobeChat)return Promise.resolve();if(loader)return loader;loader=new Promise((resolve,reject)=>{const e=document.querySelector<HTMLScriptElement>('script[data-woobe-loader="true"]');if(e){e.addEventListener('load',()=>resolve(),{once:true});e.addEventListener('error',()=>reject(new Error('Não foi possível carregar o ChatSurface')),{once:true});return}const s=document.createElement('script');s.src=SCRIPT;s.async=true;s.dataset.woobeLoader='true';s.onload=()=>resolve();s.onerror=()=>reject(new Error('Não foi possível carregar o ChatSurface'));document.head.appendChild(s)});return loader}
function clientId(){const k='mercury_store_client_id',v=localStorage.getItem(k);if(v)return v;const id=`visitor_${crypto.randomUUID()}`;localStorage.setItem(k,id);return id}
export function ChatSurfacePanel({kind,onActivity}:{kind:'store'|'admin';onActivity?:()=>void}){const container=useRef<HTMLDivElement|null>(null);const instance=useRef<{updateToken(token:string):void;destroy():void}|null>(null);const cid=useRef(clientId());const[error,setError]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false)
 async function token(){if(kind==='store'){await api.initializeStoreChat(cid.current);return api.storeChatToken(cid.current)}await api.initializeAdminChat();return api.adminChatToken()}
 async function refresh(){setRefreshing(true);try{const t=await token();instance.current?.updateToken(t.session_token);setError(null)}catch(e){setError(e instanceof Error?e.message:'Falha ao renovar')}finally{setRefreshing(false)}}
 useEffect(()=>{let cancelled=false;async function mount(){setLoading(true);setError(null);try{const t=await token();await load();if(cancelled||!container.current||!window.WoobeChat)return;instance.current=window.WoobeChat.mount({container:container.current,surfaceId:t.surface_id,sessionToken:t.session_token,iframeBaseUrl:IFRAME,apiBaseUrl:WOOBE,mode:'inline',onEvent(event){if(event.type==='session.expired')void refresh();if(event.type==='run.completed')onActivity?.()}})}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'Falha ao iniciar o assistente')}finally{if(!cancelled)setLoading(false)}}void mount();return()=>{cancelled=true;instance.current?.destroy();instance.current=null}},[kind])
 const title=kind==='store'?'Shopping Assistant':'Merchant Assistant';const subtitle=kind==='store'?'Produtos, preço, estoque e localização.':'Vendas, estoque, clientes e relatórios.'
 return <aside className={`assistant-panel ${kind}`}><div className="assistant-header"><div className="assistant-heading"><span className="assistant-icon"><Bot size={17}/></span><div><strong>{title}</strong><span>{subtitle}</span></div></div><button className="icon-button" onClick={()=>void refresh()}><RefreshCw size={15} className={refreshing?'spin':''}/></button></div><div className="assistant-body">{loading&&<div className="assistant-state"><LoaderCircle className="spin" size={18}/>Conectando…</div>}{error&&<div className="assistant-config-note"><strong>ChatSurface ainda não configurado</strong><span>{error}</span><small>A aplicação continua funcional com todos os dados mockados.</small></div>}<div ref={container} className="chat-container"/></div></aside>
}
