export interface Product { id:string; slug:string; name:string; brand:string; category:string; price:number; stock:number; available:boolean; aisle:string; shelf:string; description:string; tags:string[]; attributes:Record<string,string|number|boolean>; product_url:string }
export interface ProductSearch { count:number; results:Product[]; alternatives:Product[] }
export interface AdminMe { user_id:string; merchant_id:string; email:string; name:string; merchant_name:string }
export interface Order { id:string; customer_id:string; customer_name:string; customer_segment:string; created_at:string; status:string; total:number; items:Array<{product_id:string;product_name:string;quantity:number;unit_price:number;line_total:number}> }
export interface Dashboard { merchant:{name:string;environment:string}; metrics:{revenue_15d:number;orders_15d:number;average_order_value_15d:number;products_at_stockout_risk:number;delayed_shipments:number}; top_products:Array<{name:string;units:number;revenue:number;growth_percent:number}>; top_categories:Array<{category:string;units:number;revenue:number}>; rising_products:Array<{name:string;trend_percent:number;expected_units:number;current_stock:number}>; recent_orders:Order[] }
export interface InventoryRow { product_id:string; name:string; category:string; stock:number; price:number; expected_30d_demand:number; stock_risk:string; product_url:string }
export interface Customer { id:string; name:string; email:string; segment:string; city:string; orders_count:number; lifetime_value:number }
export interface Shipment { id:string; order_id:string; customer_id:string; customer_name:string; carrier:string; status:string; expected_at:string; last_event:string }
export interface Report { id:string; title:string; period_label:string; executive_summary:string; findings:string[]; recommendations:string[]; generated_by:string; created_at:string }
declare global { interface Window { WoobeChat?: { mount(options:{container:string|HTMLElement;surfaceId:string;sessionToken:string;mode?:'inline'|'floating';iframeBaseUrl?:string;apiBaseUrl?:string;onEvent?:(event:{type:string;payload?:unknown})=>void}):{updateToken(token:string):void;destroy():void} } } }
